import 'bootstrap/dist/css/bootstrap.min.css'
import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import Logo from "@/components/Logo"
import 'bootstrap-icons/font/bootstrap-icons.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
        <nav className='container1'>
            <ul>
              <li className="btn to-reg-button1">
                <Link href="/"  style={{ textDecoration: 'none', color:"black" }}>Home</Link>
              </li>
              <li className="btn to-reg-button2">
                <Link href="estacionamiento" style={{ textDecoration: 'none', color:"black"}}>Estacionamiento</Link>
              </li>
              <li className="btn to-reg-button3"> 
                <Link href="usuario" style={{ textDecoration: 'none', color:"black"}}>Usuarios</Link>
              </li>
              <li className="btn to-reg-button4">
                <Link href="mensajes" style={{ textDecoration: 'none', color:"black"}}>Mensajes</Link>
              </li>
            </ul>
          </nav>
          <div className='icono1'>
              <i class="bi bi-mailbox"></i>
              <Link href="login"><i className="bi bi-box-arrow-left"></i></Link>
          </div>
        </header>
        {children}
        
      </body>
    </html>
  )
}
