
export const MESSAGES = {
    OK: "OK",
    USER_EXIST: "El usuario ya existe",
    USER_NOT_FOUND: "Usuario no encontrado",
    INVALID_CREDENTIALS: "Email o contraseña invalidos",
    PASSWORD_REQUIRED: "La contraseña es requerida",
    EMAIL_REQUIRED: "El email es requerido",
    UNEXPECTED: "Error interno del servidor",
    TOKEN_EXPIRED: "El token ha expirado",
    INVALID_TOKEN: "Token invalido",
    MISSING_TOKEN: "Token no encontrado",
    ACCESS_DENIED: "Acceso denegado",
    UNAUTHORIZED: "No autorizado",
    INVALID_INPUT: "Entrada invalida",
    PASSWORD_MISMATCH: "Las contraseñas no coinciden",
    EMAIL_NOT_VERIFIED: "Email no verificado",
    EMAIL_VERIFICATION_SENT: "Link de verificación enviado",
    EMAIL_VERIFICATION_FAILED: "Verificación de email fallida",
    PASSWORD_RESET_SENT: "Instrucciones para restablecer la contraseña enviadas",
    PASSWORD_RESET_FAILED: "Restablecimiento de contraseña fallido",
    PROFILE_UPDATED: "Perfil actualizado correctamente",
    PROFILE_UPDATE_FAILED: "Actualización de perfil fallida",
    RESOURCE_NOT_FOUND: "Recurso no encontrado",
    MIME_TYPES: "Formato de imagen invalido",
    BAD_REQUEST: "Solicitud incorrecta",
    UPLOAD_SUCCESS: "Imagen subida correctamente",
    UPLOAD_NOT_FOUND: "No se han subido archivos",
    DELETE_USER_SUCCESS: "El usuario ha sido borrado con éxito",
    DELETE_USER_ERROR: "No se ha podido eliminar al usuario",
    UPDATE_USER_SUCCES: "Los datos del usuario se actualizaron con éxito"
}