
import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'

import { Inter } from 'next/font/google'
import Nabvar from '@/components/Navbar'
import 'bootstrap-icons/font/bootstrap-icons.css';
import { Suspense } from 'react';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Dashboard',
	description: 'Generated by create next app',
}

export default function DashLayout({ children }) {	




	return (

		<div className={"body" + inter.className}>
			<Nabvar />
			<Suspense>
				{children}
			</Suspense>
		</div>

	)
}