"use client"

import 'bootstrap/dist/css/bootstrap.min.css'

import './globals.css'
import { Inter } from 'next/font/google'
import Nabvar from '@/components/Navbar'
import 'bootstrap-icons/font/bootstrap-icons.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      
      <div className={ "body" +  inter.className}>
        <Nabvar/>
        <div>
          {children}
        </div>
      </div>

  )
}